### ISSUE TITLE
No indexing with LanguageClient-neovim

### ISSUE THREAD

**Issue by phil-nelson** [tsufeki/tenkawa-php-language-server#13]
I'm attempting to use this language server with [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim/). It appears to work for the file/s I have open (I get diagnostics/completion) however it doesn't seem to be award of/indexing any other files in the project (~~or the phpstorm stubs, as it tells me built in php functions don't exist~~ edit: fixed this with `--build-index`). The client does send a `rootPath` and `rootUri` in the `initialize` method message. Is there something else that needs to be done to trigger indexing?

**Comment by tsufeki** [comment]
1. Could you turn on logging by adding `--log-file=tenkawa.log --log-level=debug` to the command and see if there are any errors?

2. Indexing is pretty slow, like a few minutes even for not-very-big projects depending on your hardware (but index is stored on disk, so a full run is only needed once). Again, logs will tell you whether it has started or not.

3. If you want watching project files for changes made outside of your editor (e.g. by git or composer), on Linux you need to have `inotifywait` command installed and in `PATH` (it usually comes in `inotify-tools` package).

Thanks for taking interest in this project!

**Comment by phil-nelson** [comment]
I turned on debug and found the following in the log:

```
2018-08-23T02:00:21+00:00 pid=4999 DEBUG send: registerCapability
2018-08-23T02:00:21+00:00 pid=4999 ERROR Unhandled exception in strand #11: Tsufeki\BlancheJsonRpc\Exception\InternalException (entity not found).
    Tsufeki\BlancheJsonRpc\Exception\InternalException: entity not found in /home/foo/src/tenkawa-php-language-server/vendor/tsufeki/blanche-json-rpc/src/Tsufeki/BlancheJsonRpc/Mapper/ExceptionLoader.php:60
    Stack trace:
    #0 /home/foo/src/tenkawa-php-language-server/vendor/tsufeki/kayo-json-mapper/src/Tsufeki/KayoJsonMapper/Loader/DispatchingLoader.php(42): Tsufeki\BlancheJsonRpc\Mapper\ExceptionLoader->load(Object(stdClass), Object(phpDocumentor\Reflection\Types\Object_), Object(Tsufeki\KayoJsonMapper\Context\Context))
    #1 /home/foo/src/tenkawa-php-language-server/vendor/tsufeki/kayo-json-mapper/src/Tsufeki/KayoJsonMapper/Loader/ObjectLoader.php(127): Tsufeki\KayoJsonMapper\Loader\DispatchingLoader->load(Object(stdClass), Object(phpDocumentor\Reflection\Types\Object_), Object(Tsufeki\KayoJsonMapper\Context\Context))
    #2 /home/foo/src/tenkawa-php-language-server/vendor/tsufeki/kayo-json-mapper/src/Tsufeki/KayoJsonMapper/Loader/DispatchingLoader.php(42): Tsufeki\KayoJsonMapper\Loader\ObjectLoader->load(Object(stdClass), Object(phpDocumentor\Reflection\Types\Object_), Object(Tsufeki\KayoJsonMapper\Context\Context))
    #3 /home/foo/src/tenkawa-php-language-server/vendor/tsufeki/kayo-json-mapper/src/Tsufeki/KayoJsonMapper/Loader/UnionLoader.php(47): Tsufeki\KayoJsonMapper\Loader\DispatchingLoader->load(Object(stdClass), Object(phpDocumentor\Reflection\Types\Object_), Object(Tsufeki\KayoJsonMapper\Context\Context))
    #4 /home/foo/src/tenkawa-php-language-server/vendor/tsufeki/kayo-json-mapper/src/Tsufeki/KayoJsonMapper/Loader/DispatchingLoader.php(42): Tsufeki\KayoJsonMapper\Loader\UnionLoader->load(Object(stdClass), Object(phpDocumentor\Reflection\Types\Compound), Object(Tsufeki\KayoJsonMapper\Context\Context))
    #5 /home/foo/src/tenkawa-php-language-server/vendor/tsufeki/kayo-json-mapper/src/Tsufeki/KayoJsonMapper/Mapper.php(72): Tsufeki\KayoJsonMapper\Loader\DispatchingLoader->load(Object(stdClass), Object(phpDocumentor\Reflection\Types\Compound), Object(Tsufeki\KayoJsonMapper\Context\Context))
    #6 /home/foo/src/tenkawa-php-language-server/vendor/tsufeki/blanche-json-rpc/src/Tsufeki/BlancheJsonRpc/JsonRpc.php(172): Tsufeki\KayoJsonMapper\Mapper->load(Object(stdClass), 'Tsufeki\\Blanche...')
    #7 [internal function]: Tsufeki\BlancheJsonRpc\JsonRpc->handleMessage(Object(stdClass))
    #8 /home/foo/src/tenkawa-php-language-server/vendor/recoil/kernel/src/StrandTrait.php(146): Generator->valid()
    #9 /home/foo/src/tenkawa-php-language-server/src/Tsufeki/Tenkawa/Server/Utils/PriorityKernel/ReactScheduler.php(37): Tsufeki\Tenkawa\Server\Utils\PriorityKernel\PriorityStrand->start()
    #10 /home/foo/src/tenkawa-php-language-server/src/Tsufeki/Tenkawa/Server/Utils/PriorityKernel/ReactScheduler.php(82): Tsufeki\Tenkawa\Server\Utils\PriorityKernel\ReactScheduler->Tsufeki\Tenkawa\Server\Utils\PriorityKernel\{closure}()
    #11 /home/foo/src/tenkawa-php-language-server/vendor/react/event-loop/src/Tick/FutureTickQueue.php(46): Tsufeki\Tenkawa\Server\Utils\PriorityKernel\ReactScheduler->Tsufeki\Tenkawa\Server\Utils\PriorityKernel\{closure}()
    #12 /home/foo/src/tenkawa-php-language-server/vendor/react/event-loop/src/StreamSelectLoop.php(175): React\EventLoop\Tick\FutureTickQueue->tick()
    #13 /home/foo/src/tenkawa-php-language-server/src/Tsufeki/Tenkawa/Server/Utils/PriorityKernel/ScheduledReactKernel.php(79): React\EventLoop\StreamSelectLoop->run()
    #14 /home/foo/src/tenkawa-php-language-server/vendor/recoil/kernel/src/KernelTrait.php(76): Tsufeki\Tenkawa\Server\Utils\PriorityKernel\ScheduledReactKernel->loop()
    #15 /home/foo/src/tenkawa-php-language-server/src/Tsufeki/Tenkawa/Server/Tenkawa.php(129): Tsufeki\Tenkawa\Server\Utils\PriorityKernel\ScheduledReactKernel->run()
    #16 /home/foo/src/tenkawa-php-language-server/bin/tenkawa.php(37): Tsufeki\Tenkawa\Server\Tenkawa::main(Array)
    #17 {main}
2018-08-23T02:00:21+00:00 pid=4999 DEBUG didOpenTextDocument file:///home/foo/src/bar/public/index.php [0.0s]
2018-08-23T02:00:22+00:00 pid=4999 DEBUG Workspace diagnostics starting
2018-08-23T02:00:22+00:00 pid=4999 DEBUG Workspace diagnostics finished [0.3s]
```

The above error seems to have been in response to the following message sent by the client:

`{"jsonrpc":"2.0","error":{"code":-32603,"message":"entity not found"},"id":1}`

I think this happened because the client got "No such file or directory" when trying to use the globPattern `**/*`. in the `client/registerCapability` message:

`{"jsonrpc":"2.0","method":"client/registerCapability","params":{"registrations":[{"id":"5b7e15351906b6.08470905","method":"workspace/didChangeWatchedFiles","registerOptions":{"watchers":[{"globPattern":"**/*","kind":7}]}}]},"id":1}`

It seems that LanguageClient-neovim doesn't understand this glob (I can't find anything in the specification that specifies what sort of pattern is to be expected?). When I tested by changing `**/*` to a hard-coded path, everything then worked and indexing happened:

`INFO Indexing finished: file:///home/foo/src/bar [15289 files, 9m30.3s]`

(although seemingly a long time this is quite a large project and this seemed quite reasonable. The resulting sqlite file is 374MB)

So it seems this issue probably needs to be raised in LanguageClient-neovim (though perhaps something could be done about the exception that happened here, unless that error message that it sent is not something that should be sent according to the spec, haven't checked)

Thanks for the great project, it is looking very promising so far! :+1:

**Comment by tsufeki** [comment]
Thanks for the update.

Indeed there seems to be no specification of glob patterns in LSP (there's an issue about that Microsoft/language-server-protocol#208).

I changed `**/*` to `**`: it works the same in vscode and my quick look into LanguageClient-neovim source suggest it _may_ be better handled by it. Please see if this helps.

Also added try-catches so exception in a file watcher does not prevent regular project scan.

**Comment by phil-nelson** [comment]
Yeah your latest changes with `**` does work. Thanks for the fix! :+1:

**Comment by allan-simon** [comment]
@phil-nelson  what is your line in your init.vim config file to tell neovim to use this language server ?
