### ISSUE TITLE
annotation supports not complete

### ISSUE THREAD

**Issue by xiaohuilam** [tsufeki/tenkawa-php-language-server#22]
Hello, there is an awesome php lang server. but i found something not perfect

 - [ ] many types combine. eg: ` * @param FirstInterface|SecondInterface $interface`
 - [ ] array type define. eg: ` * @param FirstInterface[]|array $interfaces`, it means `$interfaces` should be an array, and each might be `FirstInterface`

**Comment by tsufeki** [comment]
I'm not sure I understood you right, so please correct me.

1. Do you expect `$interface` to be both `FirstInterface` and `SecondInterface` at the same time? You should use intersection type then: `@param FirstInterface&SecondInterface $interface`

2. I use [phpstan](https://github.com/phpstan/phpstan) for type analysis and it currently collapses array unions (I think it's a historical special case from times when intersection type wasn't supported):

![image](https://user-images.githubusercontent.com/4078572/50052988-7e8f7e00-012d-11e9-9ae2-d710da069c18.png)

Anyway, I don't want to override phpstan's code too much, but if you describe in more detail what you expect and *why*, I may may forward your issues to phpstan.

Thanks.

**Comment by xiaohuilam** [comment]
> Tenkawa accepts both `|` and `&`, but with different meaning: `F|S` means `F` **or** `S`, `F&S` means `F` **and** `S` at the same time.
> 
> Also I think PhpStorm supports `&` since recently.

Okay, these two were certain not able to reproduce

And i found another issue, which i posted here: #23
