### ISSUE TITLE
Possible to add additional stubs or build project-specific index?

### ISSUE THREAD

**Issue by phatsk** [tsufeki/tenkawa-php-language-server#41]
When working in WordPress projects, the built-ins, constants, etc from WordPress are undefined:

![image](https://user-images.githubusercontent.com/990374/52909063-954a7200-324f-11e9-8509-83797d87109b.png)

I found at least one LSP stubs project for WordPress, but I would have no clue how to integrate this into your LSP implementation. Is this possible/feasible.

Here's what I found: https://packagist.org/packages/giacocorsiglia/wordpress-stubs

Thanks, your LSP is the only one to work so far for me in NeoVim with any decent success.

**Comment by phatsk** [comment]
I tried my hand at a PR to allow indexing additional stubs. Something like this would work for me - it can probably be integrated with the configuration file as well.

**Comment by phatsk** [comment]
Actually, those aren't adding properly that way. Looks like it's going to need some more debugging.

**Comment by tsufeki** [comment]
It is implemented in master, add `--config-json={"index": {"stubs": ["/path/to/stubs/dir"]}}` to your server command (regular invocation, *not* `--build-index`).
