### ISSUE TITLE
Problems in loaded and import

### ISSUE THREAD

**Issue by vdjkelly** [tsufeki/tenkawa-php-language-server#60]
It takes a long time to load the basics of vs code study popr example colocon fun should load the normal public function as it does without plugin but it stays loaded...

With the extension lasts more than 10 minutes:
![imagen](https://user-images.githubusercontent.com/5873347/58796935-98822780-85cc-11e9-86ff-3f0ee6bab4e9.png)

**Comment by tsufeki** [comment]
Hi, I've published 0.4.2 which has some performance improvements, can you try out?

Did you wait until "[php] Indexing files" message disappeared? This plugin can be slow if indexing is in progress.

Also, can you please check if there are any errors in logs, like this:

![image](https://user-images.githubusercontent.com/4078572/58913227-05f09e00-871c-11e9-8e95-008d873a71c1.png)
