### ISSUE TITLE
VSCode: I cannot run the server because "I don't have the sqlite ext enabled" but I have it

### ISSUE THREAD

**Issue by lgraziani2712** [tsufeki/tenkawa-php-language-server#75]
I really have the `pdo_sqlite` extension enabled, e.g. when i run `php --info | grep sqlite` i got this response:

```
PDO drivers => mysql, sqlite
pdo_sqlite
```

and when I run a `test.php` file with the following content:

```php
<?php

echo extension_loaded('pdo_sqlite');
```

I got a `1` as a result.

- OS: Windows 10.
- PHP Version: `7.3.7`.

Thanks!

**Comment by tsufeki** [comment]
Hi, can you check if there is something in the logs? Like this:

![image](https://user-images.githubusercontent.com/4078572/64059204-dd136400-cbb7-11e9-97c3-5312e00eb8ad.png)

**Comment by lgraziani2712** [comment]
Yes! And it says nothing else 😢:

![image](https://user-images.githubusercontent.com/15050200/64071015-e7c90a00-cc46-11e9-87d6-81e1c8fc8fb4.png)

**Comment by tsufeki** [comment]
Are you sure php executable you use for `test.php` and the one in your PATH env variable are the same? Maybe PATH is changed in your console's init scripts? Try running `php --info` in a clean `cmd.exe` window. Or maybe you're using WSL? Did you set `tenkawaphp.executablePath` setting?

I'm not able to reproduce it on my windows machine :(

Thanks

**Comment by lgraziani2712** [comment]
Yes, the php from PATH env is the same. I also tried to set `tenkawaphp.executablePath`, but it throws the same message.

![image](https://user-images.githubusercontent.com/15050200/64115380-d7f41780-cd65-11e9-97ae-6ca0060261ac.png)

**Comment by lgraziani2712** [comment]
Ok. I went to the `tenkawa.php` file from my installed extension, and stored the phpinfo result in a file. What I found was that is NOT loading my `PHP_INI_SCAN_DIR` env variable (and I have both at user and system level)

**Comment by lgraziani2712** [comment]
But I really don't know why running php in my CLI is loading env vars like `PHP_INI_SCAN_DIR` but not in the extension.

If I run a php file with vscode it also uses that env var!

**Comment by lgraziani2712** [comment]
Maybe because of this? https://github.com/Microsoft/vscode/issues/2809

**Comment by tsufeki** [comment]
Oh, I got it: I accidentally override all env vars when spawning the php process. Expect a fix soon.

**Comment by tsufeki** [comment]
I've pushed new version to the marketplace, should work now. Thanks for helping!

**Comment by lgraziani2712** [comment]
Is working as expected now!

Thanks for your work!
