### ISSUE TITLE
Refactoring Issues on windows

### ISSUE THREAD

**Issue by crissi** [tsufeki/tenkawa-php-language-server#77]
Running Windows.

The folders Http and Controllers starts with a capital letter as seen in the Explorer, but it still come up as an 'error'

![image](https://user-images.githubusercontent.com/3076578/64283585-06d1df80-cf58-11e9-84d8-52d6c54ff513.png)

**Comment by tsufeki** [comment]
Should be fixed by 2c008868adf00d60dde85e7021f14d3261b4038a. Thanks for reporting.
