### ISSUE TITLE
PHP 7.4 Exception - ReflextionType::__toString() is deprecated

### ISSUE THREAD

**Issue by lumnn** [tsufeki/tenkawa-php-language-server#94]
This is an error I get when I run server with latest PHP version 7.4

```
2019-12-03T14:20:02+01:00 pid=522980 ERROR Unhandled exception in strand #1: ErrorException (Function ReflectionType::__toString() is deprecated).
    ErrorException: Function ReflectionType::__toString() is deprecated in /tmp/tenkawa-php-language-server/vendor/tsufeki/hmcontainer/src/Tsufeki/HmContainer/Wiring/Wiring.php:92
```

**Comment by lumnn** [comment]
I've created following pull requests to get language server working again:

https://github.com/tsufeki/kayo-json-mapper/pull/5
https://github.com/tsufeki/hmcontainer/pull/3

Possibly there may be more of the places where ReflectionType::__toString() is used, but I just needed server working for now, so I didn't look for them.

**Comment by tsufeki** [comment]
I fixed both deprecations in slightly different way, to be more prepared for `\ReflectionUnionType`.

Thank you very much anyway!

**Comment by lumnn** [comment]
Thanks for that!
